/*publicar*/
const SAVE_QUOTE = "SAVE_QUOTE"
const SAVING_QUOTE = "SAVING_QUOTE"
const SAVED_QUOTE = "SAVED_QUOTE"
const SAVE_QUOTE_ERROR = "SAVE_QUOTE_ERROR"

export{
    SAVE_QUOTE,
    SAVING_QUOTE,
    SAVED_QUOTE,
    SAVE_QUOTE_ERROR
}

const GET_AMIGO = "GET_AMIGO"
const GET_AMIGO_SUCCESS = "GET_AMIGO_SUCCESS"
const GET_AMIGO_ERROR = "GET_AMIGO_ERROR"

export{
    GET_AMIGO,
    GET_AMIGO_SUCCESS,
    GET_AMIGO_ERROR
}
