/*publicar*/
const SAVE_QUOTE = "SAVE_QUOTE"
const SAVING_QUOTE = "SAVING_QUOTE"
const SAVED_QUOTE = "SAVED_QUOTE"
const SAVE_QUOTE_ERROR = "SAVE_QUOTE_ERROR"

export{
    SAVE_QUOTE,
    SAVING_QUOTE,
    SAVED_QUOTE,
    SAVE_QUOTE_ERROR
}